projectName: Teacher Development Resources
jsonFilePath: ./input.json
baseUrl: https://edindia.org
portalHeading: Teacher Development Resources
portalDescription: >-
  EdIndia aims to enhance the quality of education in India by empowering
  teachers and administrators, leveraging technology and data analytics.
portalTitle: Teacher Development Resources - Enhancing Education in India
searchPlaceholder: Search for resources, programs, and more...
useAlphabetsCategory: true
homeLink: https://edindia.org/
logoLink: https://edindia.org/
ctaText: Get Started
aboutLink: https://edindia.org/about-us/
productsLink: https://edindia.org/teacher-education-training-program/
logoImgUrl: https://edindia.org/logo.png
ctaLink: https://edindia.org/join-us/
copyrightText: © 2024 All Rights Reserved, Sterlite EdIndia Foundation
faviconUrl: https://edindia.org/favicon.ico
googleTagManagerId: GTM-XXXXXX
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: LinkedIn
    url: https://in.linkedin.com/company/sterlite-edindia-foundation
  - platform: YouTube
    url: https://www.youtube.com/channel/UCxACXYD7fRisZav9746reOQ
  - platform: Instagram
    url: https://www.instagram.com/sterlite_edindia_foundation/
  - platform: Facebook
    url: https://www.facebook.com/SterliteEdIndiaFoundation/
  - platform: Twitter
    url: https://twitter.com/Edindia_EIF
theme:
  primaryColor: '#2E7D32'
  secondaryColor: '#4CAF50'
  backgroundColor: '#F5F5F5'
  textColor: '#212121'
  accentColor: '#FFEB3B'
fonts:
  - family: Roboto
    weights:
      - 400
      - 500
      - 600
  - family: Open Sans
    weights:
      - 500
      - 600
      - 700
